default: &default
  adapter: mysql2
  username: root
  password:
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: movie/development
test:
  <<: *default
  database: movie/test
production:
  <<: *default
  database: movie/production
